module.exports = {
    welcomeEmailTemplate: (name) => `Hi there, ${name}!\n\nWelcome to Stickerboards. We’re genuinely glad you decided to join.\n\nIf you’re new to using a GLP-1 medication—or if weight loss has been a frustrating, stop-and-start journey in the past—you’re not alone. Many people arrive here after putting in real effort and not seeing results that matched their commitment. Stickerboards was built with that reality in mind.\n\nThis isn’t about perfection or willpower. It’s about creating small, repeatable actions that add up over time—and giving yourself visible proof that those actions matter. Some days will feel easy. Others won’t. Both still count.\n\nStickerboards is here to support you in building consistency, noticing progress (even when it’s subtle), and staying connected to your goals in a way that feels encouraging rather than punishing.\n\nTake your time exploring. Start small. We’re rooting for you.\n\nYou’ve already taken an important step by being here.\n\nWarmly,\nThe Stickerboards Team`,
    inactivityEmailTemplate: (name) => `Hi there, ${name}\n\nWe just wanted to check in.\n\nBuilding lasting habits rarely comes from big bursts of motivation—it comes from small, consistent actions over time. Stickerboards is designed to support exactly that.\n\nIf now feels like a good moment, we’d love for you to log in and try it out. If not, that’s okay too. We’ll be here when you’re ready.\n\nWishing you steady progress,\nThe Stickerboards Team`,
    motivationalEmailTemplate: (name) => `Hi there, ${name}\n\nWe noticed you’ve been away for a bit and wanted to reach out.\n\nStaying consistent—especially during periods when motivation dips—is one of the hardest parts of any long-term goal. That’s why support systems and small positive reinforcements matter so much.\n\nTo welcome you back, we’ve added a surprise sticker pack to your account. No pressure—just something fun we hope you’ll enjoy using if and when you log in again.\n\nWhether you pick things up today or later on, remember that progress doesn’t disappear just because life gets busy. One small action is always enough to restart momentum.\n\nWe’d love to see you again when you’re ready.\n\nTake care,\nThe Stickerboards Team`
};


/*
Subject: Welcome to Stickerboards!
Hi there, ${name}!\n\nWelcome to Stickerboards. We’re genuinely glad you decided to join.\n\nIf you’re new to using a GLP-1 medication—or if weight loss has been a frustrating, stop-and-start journey in the past—you’re not alone. Many people arrive here after putting in real effort and not seeing results that matched their commitment. Stickerboards was built with that reality in mind.\n\nThis isn’t about perfection or willpower. It’s about creating small, repeatable actions that add up over time—and giving yourself visible proof that those actions matter. Some days will feel easy. Others won’t. Both still count.\n\nStickerboards is here to support you in building consistency, noticing progress (even when it’s subtle), and staying connected to your goals in a way that feels encouraging rather than punishing.\n\nTake your time exploring. Start small. We’re rooting for you.\n\nYou’ve already taken an important step by being here.\n\nWarmly,\nThe Stickerboards Team


Subject: Check-in from Stickerboards
Hi there,\n\nWe just wanted to check in.\n\nBuilding lasting habits rarely comes from big bursts of motivation—it comes from small, consistent actions over time. Stickerboards is designed to support exactly that.\n\nIf now feels like a good moment, we’d love for you to log in and try it out. If not, that’s okay too. We’ll be here when you’re ready.\n\nWishing you steady progress,\nThe Stickerboards Team


We saved something for you
Hi there, ${name}\n\n\n\nWe noticed you’ve been away for a bit and wanted to reach out.\n\nStaying consistent—especially during periods when motivation dips—is one of the hardest parts of any long-term goal. That’s why support systems and small positive reinforcements matter so much.\n\nTo welcome you back, we’ve added a surprise sticker pack to your account. No pressure—just something fun we hope you’ll enjoy using if and when you log in again.\n\nWhether you pick things up today or later on, remember that progress doesn’t disappear just because life gets busy. One small action is always enough to restart momentum.\n\nWe’d love to see you again when you’re ready.\n\nTake care,\nThe Stickerboards Team
 */